version: '3.9'
services:
  db:
    image: postgres:17.2-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
    ports:
      - "5432:5433"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: